version: '3.6'

services:
  iron-vault:
    image: postgres:12.5-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "me"
      POSTGRES_PASSWORD: "password"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    volumes:
      - "iron-vault-data:/var/lib/postgresql/data"
      - "./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - rainbow-bridge

  monitoring-demo-app:
    image: monitoring-demo:latest
    restart: always
    volumes:
      - "./misc/logback.elastic.xml:/app/resources/logback.xml"
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/elastic-apm-agent-1.19.0.jar -Delastic.apm.service_name=monitoring-demo-app -Delastic.apm.server_url=http://apm-server:8200 -Delastic.apm.application_packages=hu"
      APP_ID: "monitoring-demo-app"
    networks:
      - rainbow-bridge
    depends_on:
      - iron-vault
      - elasticsearch

  metricbeat:
    image: docker.elastic.co/beats/metricbeat-oss:7.10.1
    user: root
    restart: always
    volumes:
      - "./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/proc:/hostfs/proc:ro"
      - "/:/hostfs:ro"
    networks:
      - rainbow-bridge
    depends_on:
      - iron-vault
      - edge-service
      - kibana

  edge-service:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./edgeservice/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - rainbow-bridge
    depends_on:
      - elasticsearch
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    restart: always
    volumes:
      - "./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "elastic-data:/usr/share/elasticsearch/data"
    environment:
      ELASTIC_PASSWORD: "password"
    networks:
      - rainbow-bridge

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    restart: always
    volumes:
      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    depends_on:
      - elasticsearch
    networks:
      - rainbow-bridge

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.10.1
    restart: always
    networks:
      - rainbow-bridge
    volumes:
      - "./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro"
    depends_on: [ 'elasticsearch', 'kibana' ]

networks:
  rainbow-bridge:
    driver: bridge

volumes:
  iron-vault-data:
    driver: local
  elastic-data:
    driver: local
