apm-server.frontend.enabled: true
apm-server.host: "0.0.0.0:8200"

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "http"
  username: elastic
  password: "password"

setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: "password"
  protocol: "http"
